# Pandas Mastery

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/muhammadtalhaishtiaq/ai-orchestrator/blob/main/00-foundations/python-essentials/03_pandas_mastery.ipynb)

**Time**: ~20 minutes

## What You'll Learn
- DataFrames and Series
- Loading and exploring data
- Filtering, selecting, and transforming
- GroupBy and aggregations

## Why Pandas?

Real data comes in tables (CSV, Excel, databases). Pandas is how you load it, clean it, and prep it for ML. You'll spend 80% of your time here.

In [1]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")

Pandas version: 2.2.2

---
## 1. Creating DataFrames

In [2]:
# From dictionary - most common way
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'age': [25, 30, 35, 28],
    'salary': [50000, 60000, 75000, 55000],
    'department': ['Engineering', 'Marketing', 'Engineering', 'Sales']
}

df = pd.DataFrame(data)

In [3]:
# Quick look at the data
print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
print(f"\nData types:\n{df.dtypes}")

Shape: (4, 4)
Columns: ['name', 'age', 'salary', 'department']

Data types:
name          object
age            int64
salary         int64
department    object
dtype: object

In [4]:
# Load from CSV (most common in real projects)
# df = pd.read_csv('data.csv')

# We'll create a sample dataset
np.random.seed(42)
n = 100

df = pd.DataFrame({
    'age': np.random.randint(20, 60, n),
    'income': np.random.randint(30000, 120000, n),
    'experience': np.random.randint(0, 30, n),
    'education': np.random.choice(['High School', 'Bachelor', 'Master', 'PhD'], n),
    'purchased': np.random.choice([0, 1], n)
})

df.head(10)

   age  income  experience    education  purchased
0   58  119135          15          PhD          0
1   48   65222          15          PhD          1
2   34  107373           0          PhD          1
3   27  109575           8          PhD          0
4   40  114651          27       Master          0
5   58   93335          26       Master          1
6   38   40965           5  High School          0
7   42   54538          15          PhD          1
8   30  100592          28  High School          0
9   30   38110           2          PhD          1

---
## 2. Exploring Data

In [5]:
# First and last rows
print("First 3 rows:")
display(df.head(3))

print("\nLast 3 rows:")
display(df.tail(3))

First 3 rows:

   age  income  experience education  purchased
0   58  119135          15       PhD          0
1   48   65222          15       PhD          1
2   34  107373           0       PhD          1

Last 3 rows:

    age  income  experience    education  purchased
97   31   95733          13          PhD          1
98   53  119045          20  High School          0
99   52   64698          15  High School          0

In [6]:
# Summary stats - your first step with any dataset
df.describe()

              age         income  experience  purchased
count  100.000000     100.000000  100.000000     100.00
mean    38.790000   78526.890000   14.100000       0.55
std     11.556008   25930.444385    9.338202       0.50
min     20.000000   30206.000000    0.000000       0.00
25%     28.000000   55789.750000    5.750000       0.00
50%     39.500000   81544.000000   15.000000       1.00
75%     47.250000   98107.250000   22.250000       1.00
max     59.000000  119474.000000   29.000000       1.00

In [7]:
# Info about columns and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         100 non-null    int64
 1   income      100 non-null    int64
 2   experience  100 non-null    int64
 3   education   100 non-null    object
 4   purchased   100 non-null    int64
dtypes: int64(4), object(1)
memory usage: 4.0+ KB

In [8]:
# Value counts for categorical columns
df['education'].value_counts()

education
PhD            28
High School    25
Bachelor       24
Master         23
Name: count, dtype: int64

---
## 3. Selecting Data

In [9]:
# Single column (returns Series)
ages = df['age']
print(f"Type: {type(ages)}")
print(f"First 5: {ages.head().tolist()}")

Type: <class 'pandas.core.series.Series'>
First 5: [58, 48, 34, 27, 40]

In [10]:
# Multiple columns (returns DataFrame)
subset = df[['age', 'income', 'purchased']]
subset.head()

   age  income  purchased
0   58  119135          0
1   48   65222          1
2   34  107373          1
3   27  109575          0
4   40  114651          0

In [11]:
# loc - select by label
# iloc - select by position

# First 5 rows, specific columns
df.loc[:4, ['age', 'income']]

   age  income
0   58  119135
1   48   65222
2   34  107373
3   27  109575
4   40  114651

In [12]:
# By position
df.iloc[0:5, 0:3]  # First 5 rows, first 3 columns

   age  income  experience
0   58  119135          15
1   48   65222          15
2   34  107373           0
3   27  109575           8
4   40  114651          27

---
## 4. Filtering Data

In [13]:
# Simple filter
high_income = df[df['income'] > 80000]
print(f"High income count: {len(high_income)}")
high_income.head()

High income count: 54

   age  income  experience education  purchased
0   58  119135          15       PhD          0
2   34  107373           0       PhD          1
3   27  109575           8       PhD          0
4   40  114651          27    Master          0
5   58   93335          26    Master          1

In [14]:
# Multiple conditions (use & for AND, | for OR)
filtered = df[(df['age'] > 30) & (df['income'] > 60000)]
print(f"Age > 30 AND income > 60k: {len(filtered)} rows")
filtered.head()

Age > 30 AND income > 60k: 49 rows

   age  income  experience education  purchased
0   58  119135          15       PhD          0
1   48   65222          15       PhD          1
2   34  107373           0       PhD          1
4   40  114651          27    Master          0
5   58   93335          26    Master          1

In [15]:
# Filter with isin()
advanced = df[df['education'].isin(['Master', 'PhD'])]
print(f"Advanced degrees: {len(advanced)} rows")

Advanced degrees: 51 rows

---
## 5. Creating New Columns

In [16]:
# Simple calculation
df['income_per_year_exp'] = df['income'] / (df['experience'] + 1)

# Conditional column
df['income_level'] = df['income'].apply(
    lambda x: 'High' if x > 80000 else 'Medium' if x > 50000 else 'Low'
)

df[['income', 'experience', 'income_per_year_exp', 'income_level']].head(10)

   income  experience  income_per_year_exp income_level
0  119135          15          7445.937500         High
1   65222          15          4076.375000       Medium
2  107373           0        107373.000000         High
3  109575           8         12175.000000         High
4  114651          27          4094.678571         High
5   93335          26          3456.851852         High
6   40965           5          6827.500000          Low
7   54538          15          3408.625000       Medium
8  100592          28          3468.689655         High
9   38110           2         12703.333333          Low

In [17]:
# Using np.where (like if-else)
df['is_senior'] = np.where(df['age'] >= 40, 1, 0)
df[['age', 'is_senior']].head(10)

   age  is_senior
0   58          1
1   48          1
2   34          0
3   27          0
4   40          1
5   58          1
6   38          0
7   42          1
8   30          0
9   30          0

---
## 6. GroupBy - Aggregate by Category

In [18]:
# Average income by education level
df.groupby('education')['income'].mean().sort_values(ascending=False)

education
PhD            81317.821429
Bachelor       80868.375000
Master         79530.347826
High School    72230.040000
Name: income, dtype: float64

In [19]:
# Multiple aggregations
df.groupby('education').agg({
    'income': ['mean', 'std', 'count'],
    'age': 'mean'
}).round(2)

               income                    age
                 mean       std count   mean
education
Bachelor     80868.38  30585.13    24  40.62
High School  72230.04  22578.41    25  37.12
Master       79530.35  26022.33    23  41.78
PhD          81317.82  24761.51    28  36.25

In [20]:
# Crosstab - count combinations
pd.crosstab(df['education'], df['purchased'])

purchased     0   1
education
Bachelor     11  13
High School  14  11
Master        9  14
PhD          11  17

---
## 7. Handling Missing Values

In [21]:
# Add some missing values for demo
df_missing = df.copy()
df_missing.loc[0:5, 'income'] = np.nan
df_missing.loc[10:15, 'age'] = np.nan

# Check for missing values
print("Missing values per column:")
print(df_missing.isnull().sum())

Missing values per column:
age                    6
income                 6
experience             0
education              0
purchased              0
income_per_year_exp    0
income_level           0
is_senior              0
dtype: int64

In [22]:
# Fill with mean
df_filled = df_missing.copy()
df_filled['income'] = df_filled['income'].fillna(df_filled['income'].mean())
df_filled['age'] = df_filled['age'].fillna(df_filled['age'].median())

print("After filling:")
print(df_filled.isnull().sum())

After filling:
age                    0
income                 0
experience             0
education              0
purchased              0
income_per_year_exp    0
income_level           0
is_senior              0
dtype: int64

---
## Quick Reference

| Operation | Code |
|-----------|------|
| Load CSV | `pd.read_csv('file.csv')` |
| Summary stats | `df.describe()` |
| Filter rows | `df[df['col'] > value]` |
| Select columns | `df[['col1', 'col2']]` |
| Group and aggregate | `df.groupby('col')['val'].mean()` |
| Check missing | `df.isnull().sum()` |
| Fill missing | `df['col'].fillna(value)` |
| New column | `df['new'] = df['a'] + df['b']` |

---
## Your Turn

1. Create a DataFrame with 200 random customers (age, income, city, product_bought)
2. Find the average income per city
3. Create a column 'age_group' (Young/Middle/Senior based on age)
4. Find which age group buys the most

In [23]:
# Your code here